"""grok-utils hooks - list, validate and scaffold lifecycle hooks."""

from __future__ import annotations

from pathlib import Path

import typer

from ..utils.common import (
    console,
    error,
    get_grok_home,
    info,
    make_table,
    success,
    warn,
)
from ..utils.parsers import iter_hooks, parse_hooks

app = typer.Typer(
    help="Hooks inspection and scaffolding (SessionStart, PreToolUse, etc.)", no_args_is_help=True
)


@app.command("list")
def list_hooks(
    ctx: typer.Context,
    event: str | None = typer.Option(
        None, "--event", "-e", help="Filter to specific event e.g. SessionStart"
    ),
    json_out: bool = typer.Option(False, "--json"),
) -> None:
    """List hooks by event type across user/project and plugin locations."""
    grok_home = get_grok_home(ctx.obj.get("grok_home") if ctx.obj else None)
    hooks = iter_hooks(grok_home)

    if event:
        hooks = [h for h in hooks if h.event.lower() == event.lower()]

    if json_out:
        import json

        console.print(
            json.dumps(
                [
                    {
                        "event": h.event,
                        "scope": h.scope,
                        "entries": h.entries,
                        "path": str(h.path),
                        "sample_commands": h.commands[:2],
                    }
                    for h in hooks
                ],
                indent=2,
            )
        )
        return

    if not hooks:
        warn("No hooks.json found in ~/.grok/hooks, .grok/hooks or plugin dirs.")
        info(
            "See docs: https://github.com (user-guide 10-hooks.md) or run `grok-utils hooks create`"
        )
        return

    t = make_table(f"Hooks ({len(hooks)})", ["Event", "Scope", "Entries", "Sample", "File"])
    for h in hooks:
        sample = h.commands[0][:45] + "…" if h.commands else "—"
        t.add_row(h.event, h.scope, str(h.entries), sample, str(h.path.name))
    console.print(t)


@app.command("create")
def create_hook(
    ctx: typer.Context,
    event: str = typer.Argument(..., help="Event name e.g. SessionStart, PostToolUse, PreToolUse"),
    name: str = typer.Option("my-hook", "--name", "-n", help="Base name for the hook file"),
    out: str | None = typer.Option(
        None, "--out", "-o", help="Output file path (default: ~/.grok/hooks/<name>.json)"
    ),
) -> None:
    """Scaffold a starter hooks.json for the given event."""
    grok_home = get_grok_home(ctx.obj.get("grok_home") if ctx.obj else None)

    default_path = grok_home / "hooks" / f"{name}.json"
    target = Path(out) if out else default_path
    target.parent.mkdir(parents=True, exist_ok=True)

    if target.exists():
        error(f"{target} already exists. Use --out for a different path.")
        raise typer.Exit(1)

    # Simple safe template (command example)
    template = f"""{{
  "description": "Custom {event} hook generated by grok-utils",
  "hooks": {{
    "{event}": [
      {{
        "hooks": [
          {{
            "type": "command",
            "command": "echo 'Grok {event} hook fired in $(pwd)'",
            "timeout": 30
          }}
        ]
      }}
    ]
  }}
}}
"""
    target.write_text(template, encoding="utf-8")
    success(f"Created {target}")
    info(
        "Edit the command, add matchers/if conditions, then restart your grok session or run /hooks reload."
    )
    info("Validate with: grok-utils hooks validate " + str(target))


@app.command("validate")
def validate_hooks(
    ctx: typer.Context,
    path: str | None = typer.Argument(None, help="Specific hooks.json to validate (default: all)"),
    json_out: bool = typer.Option(False, "--json"),
) -> None:
    """Basic structural validation of hooks files."""
    grok_home = get_grok_home(ctx.obj.get("grok_home") if ctx.obj else None)

    if path:
        files = [Path(path)]
    else:
        # collect from iter
        hooks = iter_hooks(grok_home)
        files = list({h.path for h in hooks})

    results = []
    for hf in files:
        hooks = parse_hooks(hf, scope="check")
        ok = len(hooks) > 0
        results.append({"file": str(hf), "events": [h.event for h in hooks], "ok": ok})

    if json_out:
        import json

        console.print(json.dumps(results, indent=2))
        return

    t = make_table("Hooks Validation", ["File", "Events", "Status"])
    for r in results:
        status = "✓" if r["ok"] else "✗ (no parsable events)"
        fpath = str(r.get("file", ""))
        raw_evs = r.get("events") or []
        ev_list: list[str] = [str(x) for x in raw_evs] if isinstance(raw_evs, (list, tuple)) else []
        t.add_row(fpath[:50], ",".join(ev_list) or "—", status)
    console.print(t)


@app.command("doctor")
def hooks_doctor(ctx: typer.Context) -> None:
    """Quick health summary for hooks (count + locations)."""
    grok_home = get_grok_home(ctx.obj.get("grok_home") if ctx.obj else None)
    hooks = iter_hooks(grok_home)
    if not hooks:
        warn("No hooks discovered.")
        return
    by_event: dict[str, int] = {}
    for h in hooks:
        by_event[h.event] = by_event.get(h.event, 0) + 1
    console.print(
        f"[bold]Hooks doctor[/bold] — {len(hooks)} entries across {len(by_event)} event types"
    )
    for ev, cnt in sorted(by_event.items()):
        console.print(f"  {ev}: {cnt}")
    success("Hooks are being discovered (restart grok session to activate changes).")
