"""Parsers for Grok-specific file formats (SKILL.md frontmatter, etc)."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from .common import find_repo_root, safe_json_load, safe_read_text

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


@dataclass
class Skill:
    name: str
    description: str
    path: Path
    scope: str = "user"
    content: str = ""
    frontmatter: dict[str, Any] = field(default_factory=dict)

    @property
    def is_valid(self) -> bool:
        return bool(self.name and self.description)


def parse_skill(skill_dir: Path, scope: str = "user") -> Skill | None:
    """Parse a skill directory. Returns None if no/invalid SKILL.md."""
    md = skill_dir / "SKILL.md"
    if not md.exists():
        return None
    try:
        text = md.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None

    fm: dict[str, Any] = {}
    body = text
    m = FRONTMATTER_RE.search(text)
    if m:
        try:
            fm = yaml.safe_load(m.group(1)) or {}
            body = text[m.end() :]
        except Exception:  # yaml parse errors are varied; keep broad here
            fm = {}

    name = fm.get("name") or skill_dir.name
    desc = fm.get("description") or (body.strip().split("\n\n")[0][:200] if body.strip() else "")

    return Skill(
        name=str(name).strip().lower(),
        description=str(desc).strip(),
        path=skill_dir,
        scope=scope,
        content=body.strip(),
        frontmatter=fm,
    )


def iter_skills(grok_home: Path) -> list[Skill]:
    """Discover and parse all skills from known locations (higher prio first, dedup names)."""
    from .common import get_skills_dirs

    seen: set[str] = set()
    results: list[Skill] = []
    for scope, sdir in get_skills_dirs(grok_home):
        if not sdir or not sdir.exists():
            continue
        for child in sorted(sdir.iterdir()):
            if not child.is_dir():
                continue
            skill = parse_skill(child, scope=scope)
            if skill and skill.name not in seen:
                seen.add(skill.name)
                results.append(skill)
    return results


def validate_skill(skill: Skill) -> list[str]:
    """Return list of validation error messages (empty = valid)."""
    errs: list[str] = []
    if not skill.name or len(skill.name) > 64:
        errs.append("name must be 1-64 chars, lowercase with hyphens ok")
    if not skill.description or len(skill.description) < 10:
        errs.append("description must be at least 10 chars (used for auto-invocation)")
    if "name" not in skill.frontmatter:
        errs.append("frontmatter missing required 'name'")
    if "description" not in skill.frontmatter:
        errs.append("frontmatter missing required 'description'")
    # check for basic steps or content
    if len(skill.content) < 30:
        errs.append("SKILL.md body looks very short; add steps/instructions")
    return errs


def skill_template(name: str, description: str) -> str:
    """Generate a high-quality starter SKILL.md."""
    slug = name.lower().replace(" ", "-").replace("_", "-")
    return f"""---
name: {slug}
description: {description}
---

# {name.title()}

{description}

## When to use

- Trigger phrase 1...
- Trigger phrase 2...

## Steps

1. ...
2. Run the appropriate command/tool
3. Verify output and summarize for the user

## Best Practices

- Always ...
- Never ...
- Prefer ...

## Examples

```bash
# example invocation
```

## Notes

- This skill was generated by grok-utils skills create
"""


# -----------------------------
# Plugins (Tier 1)
# -----------------------------
@dataclass
class Plugin:
    name: str
    path: Path
    scope: str = "user"
    version: str = ""
    description: str = ""
    author: str = ""
    has_skills: bool = False
    has_agents: bool = False
    has_hooks: bool = False
    has_mcp: bool = False
    components: list[str] = field(default_factory=list)

    @property
    def is_valid(self) -> bool:
        return bool(self.name)


def _looks_like_plugin(p: Path) -> bool:
    if not p.exists():
        return False
    if p.is_dir():
        markers = [
            "skills",
            "agents",
            "hooks",
            ".mcp.json",
            ".lsp.json",
            "plugin.json",
            "manifest.json",
        ]
        return any((p / m).exists() for m in markers)
    return False


def parse_plugin(plugin_dir: Path, scope: str = "user") -> Plugin | None:
    """Parse a plugin directory or manifest. Best effort, very tolerant."""
    if not _looks_like_plugin(plugin_dir):
        return None
    name = plugin_dir.name
    version = ""
    desc = ""
    author = ""
    manifest = plugin_dir / "plugin.json"
    if not manifest.exists():
        manifest = plugin_dir / ".claude-plugin" / "plugin.json"
    if manifest.exists():
        text = safe_read_text(manifest)
        data = safe_json_load(text, default={})
        name = data.get("name", name)
        version = data.get("version", "")
        desc = data.get("description", "")
        a = data.get("author", {})
        if isinstance(a, dict):
            author = a.get("name", "")
        elif isinstance(a, str):
            author = a

    has_skills = (plugin_dir / "skills").exists() or bool(list((plugin_dir).rglob("SKILL.md")))
    has_agents = (plugin_dir / "agents").exists()
    has_hooks = (plugin_dir / "hooks" / "hooks.json").exists() or (plugin_dir / "hooks").exists()
    has_mcp = (plugin_dir / ".mcp.json").exists()

    comps: list[str] = []
    if has_skills:
        comps.append("skills")
    if has_agents:
        comps.append("agents")
    if has_hooks:
        comps.append("hooks")
    if has_mcp:
        comps.append("mcp")

    return Plugin(
        name=str(name).strip(),
        path=plugin_dir,
        scope=scope,
        version=version,
        description=desc[:200],
        author=author,
        has_skills=has_skills,
        has_agents=has_agents,
        has_hooks=has_hooks,
        has_mcp=has_mcp,
        components=comps,
    )


def iter_plugins(grok_home: Path, include_marketplace: bool = False) -> list[Plugin]:
    """Discover plugins from standard locations. Dedup by name (higher scope wins)."""
    import os as _os  # local alias to avoid top level if not wanted

    from .common import get_plugin_dirs

    seen: set[str] = set()
    results: list[Plugin] = []
    for scope, pdir in get_plugin_dirs(grok_home):
        if not pdir or not pdir.exists():
            continue
        for child in sorted(pdir.iterdir()):
            if child.name.startswith("."):
                continue
            pl = parse_plugin(child, scope=scope)
            if pl and pl.name and pl.name.lower() not in seen:
                seen.add(pl.name.lower())
                results.append(pl)

    if include_marketplace:
        try:
            import os as _os

            cache = grok_home / "marketplace-cache"
            if cache.exists():
                for root, dirs, _ in _os.walk(cache):
                    for d in dirs:
                        cand = Path(root) / d
                        if _looks_like_plugin(cand) or (cand / ".claude-plugin").exists():
                            pl = parse_plugin(cand, scope="marketplace")
                            if pl and pl.name.lower() not in seen:
                                seen.add(pl.name.lower())
                                results.append(pl)
        except (OSError, PermissionError, RuntimeError):
            pass
    return results


def validate_plugin(pl: Plugin) -> list[str]:
    errs: list[str] = []
    if not pl.name:
        errs.append("missing name")
    if not (pl.has_skills or pl.has_agents or pl.has_hooks or pl.has_mcp):
        errs.append("no recognizable components (skills/agents/hooks/mcp)")
    return errs


# -----------------------------
# Hooks (Tier 1)
# -----------------------------
@dataclass
class Hook:
    event: str
    path: Path
    scope: str = "user"
    entries: int = 0
    commands: list[str] = field(default_factory=list)
    description: str = ""


def parse_hooks(hooks_file: Path, scope: str = "user") -> list[Hook]:
    """Parse a hooks.json file. Returns list of Hook per event."""
    if not hooks_file.exists():
        return []
    text = safe_read_text(hooks_file)
    if not text:
        return []
    try:
        data = json.loads(text)
    except (json.JSONDecodeError, TypeError, UnicodeDecodeError):
        return []

    desc = data.get("description", "") if isinstance(data, dict) else ""
    hooks_section = data.get("hooks", {}) if isinstance(data, dict) else {}
    results: list[Hook] = []
    if isinstance(hooks_section, dict):
        for event, entries in hooks_section.items():
            cmds: list[str] = []
            count = 0
            if isinstance(entries, list):
                for e in entries:
                    if isinstance(e, dict):
                        for h in e.get("hooks", []):
                            if isinstance(h, dict) and h.get("type") == "command":
                                c = h.get("command", "")
                                if c:
                                    cmds.append(str(c)[:120])
                            count += 1
            results.append(
                Hook(
                    event=str(event),
                    path=hooks_file,
                    scope=scope,
                    entries=count or len(cmds),
                    commands=cmds[:5],
                    description=str(desc)[:120],
                )
            )
    return results


def iter_hooks(grok_home: Path) -> list[Hook]:
    """Collect all hooks from known hook dirs and also from inside discovered plugins."""
    from .common import get_hooks_dirs

    out: list[Hook] = []
    for scope, hdir in get_hooks_dirs(grok_home):
        if not hdir or not hdir.exists():
            continue
        for jf in sorted(hdir.glob("*.json")):
            out.extend(parse_hooks(jf, scope=scope))
        for jf in hdir.rglob("hooks.json"):
            out.extend(parse_hooks(jf, scope=scope))

    # Also pull from plugins that ship hooks
    try:
        for pl in iter_plugins(grok_home):
            ph = pl.path / "hooks" / "hooks.json"
            if ph.exists():
                for hk in parse_hooks(ph, scope=f"plugin:{pl.name}"):
                    out.append(hk)
    except Exception:
        pass
    return out


# -----------------------------
# Config helpers (Tier 2)
# -----------------------------
def load_config(grok_home: Path) -> dict[str, Any]:
    """Load config.toml (delegates to common.load_toml for tomllib/tomli/naive)."""
    from .common import get_config_path, load_toml

    cfg_path = get_config_path(grok_home)
    return load_toml(cfg_path)


# -----------------------------
# Deep session data (for analyze / rewind / export)
# -----------------------------
@dataclass
class SessionSignals:
    session_id: str
    turn_count: int = 0
    tool_call_count: int = 0
    error_count: int = 0
    compaction_count: int = 0
    context_tokens_used: int = 0
    context_window_tokens: int = 0
    tools_used: list[str] = field(default_factory=list)
    models_used: list[str] = field(default_factory=list)
    session_duration_s: int = 0
    agent_files_touched: int = 0
    raw: dict[str, Any] = field(default_factory=dict)


def load_session_signals(session_path: Path) -> SessionSignals | None:
    sigf = session_path / "signals.json"
    if not sigf.exists():
        return None
    text = safe_read_text(sigf)
    if not text:
        return None
    try:
        data = json.loads(text)
        return SessionSignals(
            session_id=session_path.name,
            turn_count=data.get("turnCount", 0),
            tool_call_count=data.get("toolCallCount", 0),
            error_count=data.get("errorCount", 0),
            compaction_count=data.get("compactionCount", 0),
            context_tokens_used=data.get("contextTokensUsed", 0),
            context_window_tokens=data.get("contextWindowTokens", 0),
            tools_used=data.get("toolsUsed", []) or [],
            models_used=data.get("modelsUsed", []) or [],
            session_duration_s=data.get("sessionDurationSeconds", 0),
            agent_files_touched=data.get("agentFilesTouched", 0),
            raw=data,
        )
    except (json.JSONDecodeError, TypeError, KeyError, ValueError):
        return None


@dataclass
class RewindPoint:
    prompt_index: int
    created_at: str | None = None
    num_file_snapshots: int = 0


def load_rewind_points(session_path: Path, limit: int = 20) -> list[RewindPoint]:
    rpf = session_path / "rewind_points.jsonl"
    if not rpf.exists():
        return []
    out: list[RewindPoint] = []
    text = safe_read_text(rpf)
    if not text:
        return out
    for i, line in enumerate(text.splitlines()):
        if i >= limit:
            break
        try:
            d = json.loads(line)
            out.append(
                RewindPoint(
                    prompt_index=d.get("prompt_index", i),
                    created_at=d.get("created_at"),
                    num_file_snapshots=len(d.get("file_snapshots", {})),
                )
            )
        except (json.JSONDecodeError, TypeError, KeyError, ValueError):
            continue
    return out


# -----------------------------
# Logs (simple)
# -----------------------------
def tail_logs(grok_home: Path, lines: int = 50, level: str | None = None) -> list[dict]:
    from .common import get_logs_path

    lp = get_logs_path(grok_home)
    if not lp.exists():
        return []
    out: list[dict] = []
    text = safe_read_text(lp)
    if not text:
        return out
    all_lines = text.splitlines()[-lines * 2 :]
    for raw in all_lines[-lines:]:
        try:
            d = json.loads(raw)
            if level and d.get("lvl", "").lower() != level.lower():
                continue
            out.append(d)
        except (json.JSONDecodeError, TypeError, KeyError, AttributeError):
            continue
    return out


# -----------------------------
# Simple project rules / AGENTS discovery (Tier 2/3 stub)
# -----------------------------
def iter_project_rules() -> list[Path]:
    """Find AGENTS.md or .grok/rules in cwd/repo (very lightweight)."""
    out: list[Path] = []
    cwd = Path.cwd()
    for cand in [cwd / "AGENTS.md", cwd / ".grok" / "rules.md", cwd / "rules.md"]:
        if cand.exists():
            out.append(cand)
    repo = find_repo_root()
    if repo:
        for cand in [repo / "AGENTS.md", repo / ".grok" / "rules.md"]:
            if cand.exists() and cand not in out:
                out.append(cand)
    return out
